### ISSUE TITLE
No such file or directory domainname all txt file

### ISSUE THREAD

**Issue by oldesec** [TypeError/domained#37]
Hello,

When I enter the command, the following error occurs.

command line :  python domained.py -q -d  google.com

```
subfinder Complete

 Opening Sublist3r File

Error Opening Sublist3r File!


 Opening knock File

Error Opening knock File!


 Opening enumall File

Error Opening enumall File!


 Opening massdns File

Error Opening massdns File!


 Opening amass File

Error Opening amass File!


 Opening SubFinder File

Error Opening SubFinder File!


Combining Domains Lists

Traceback (most recent call last):
  File "domained.py", line 496, in <module>
    options()
  File "domained.py", line 470, in options
    subdomainfile()
  File "domained.py", line 342, in subdomainfile
    with open(subdomainAllFile, "r") as domainList:
IOError: [Errno 2] No such file or directory: 'output/google.com-all.txt'
```

**Comment by oldesec** [comment]
In my opinion, there seems to be a problem with 995a70bf2a2f3ca92f86784acf1b834c25136d73

On earlier versions (4dd6fe84a72fd65dbe4362738d167cceb5d5f407), no errors are generated.

**Comment by cak** [comment]
Thanks @oldesec! I am hoping to take time soon for a complete rewrite, but in the mean time I pushed a quick fix.

**Comment by oldesec** [comment]
Hello @cak  Anyway, the problem of disability has disappeared. :)

I think it would be better to add an option to use the "aquatone" tool.

Because the "EyeWitness" tool is very slow.

**Comment by mzfr** [comment]
@oldesec 	Thanks for the suggestion we'll look into that.
