### ISSUE TITLE
Maintainers Wanted

### ISSUE THREAD

**Issue by cak** [TypeError/domained#42]
I am currently on a hiatus from bug bounty hunting and it would be awesome if there was anyone interested in helping maintain `domained`. 

If you are, please let me know.

Being the top contributors 🤩, @ccsplit, @mzfr, @apoorvrajsaxena would any of you be interested?

**Comment by mzfr** [comment]
@cak 	Yeah sure.

**Comment by apoorvrajsaxena** [comment]
Yeah, happy to help.

**Comment by ccsplit** [comment]
I can help out when I have time.

**Comment by cak** [comment]
🚀  Thanks! You all rock!

**Comment by cak** [comment]
All, I think it is time to archive `domained`. I appreciate all your help over the years @mzfr @secxena and @ccsplit - you are welcome to fork it and I will add a link to the new location if you want.  ``
