### ISSUE TITLE
from shutil import which | cannot import which(import error)

### ISSUE THREAD

**Issue by HasaanCh** [TypeError/domained#49]
I am running the script in Parrot OS. All the requirements are complete. Parrot OS come with recon-ng preinstalled. 
These are the results : 
`pip install -r ./ext/requirements.txt
Requirement already satisfied: argparse in /usr/lib/python2.7 (from -r ./ext/requirements.txt (line 1)) (1.2.1)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from -r ./ext/requirements.txt (line 2)) (2.21.0)
Requirement already satisfied: datetime in /usr/local/lib/python2.7/dist-packages (from -r ./ext/requirements.txt (line 3)) (4.3)
Requirement already satisfied: ConfigParser in /usr/lib/python2.7/dist-packages (from -r ./ext/requirements.txt (line 4)) (3.5.0b2)
Requirement already satisfied: secure-smtplib in /usr/local/lib/python2.7/dist-packages (from -r ./ext/requirements.txt (line 5)) (0.1.1)
Requirement already satisfied: netaddr in /usr/lib/python2.7/dist-packages (from -r ./ext/requirements.txt (line 6)) (0.7.19)
Requirement already satisfied: zope.interface in /usr/lib/python2.7/dist-packages (from datetime->-r ./ext/requirements.txt (line 3)) (4.3.2)
Requirement already satisfied: pytz in /usr/lib/python2.7/dist-packages (from datetime->-r ./ext/requirements.txt (line 3)) (2019.1)`

`python domained.py 
Traceback (most recent call last):
  File "domained.py", line 29, in <module>
    from shutil import which
ImportError: cannot import name which
`

**Comment by mzfr** [comment]
@HasaanCh 	You are getting this error because you are using `python2`. You won't have this issue if you use `python3`

**Comment by HasaanCh** [comment]
> @HasaanCh You are getting this error because you are using `python2`. You won't have this issue if you use `python3`

Thanks a lot <3. It worked.
