### ISSUE TITLE
installation issue!!!

### ISSUE THREAD

**Issue by Sechunt3r** [TypeError/domained#55]
python domained.py --install
Traceback (most recent call last):
  File "domained.py", line 29, in <module>
    from shutil import which
ImportError: cannot import name which

 pip install which
Collecting which
  ERROR: Could not find a version that satisfies the requirement which (from versions: none)
ERROR: No matching distribution found for which

**Comment by ccsplit** [comment]
Please use python 3.4+.

**Comment by mzfr** [comment]
@Sechunt3r 	DO you still have this issue?

**Comment by Quiquello12** [comment]
@Sechunt3r instead of "python domained.py --install" you have to run "python3 domained.py --install" I encountered the same problem.

**Comment by mzfr** [comment]
This will be fixed by the use of python3
