### ISSUE TITLE
a request

### ISSUE THREAD

**Issue by 687766616e** [TypeError/domained#56]
can you add data source zoomeye.org and fofa.so to your repo? (You don't have to use the API!

**Comment by mzfr** [comment]
@huitc can you please explain what is this for?

**Comment by huitc** [comment]
sub finder? i think~... ^^''

**Comment by apoorvrajsaxena** [comment]
test

**Comment by 687766616e** [comment]
@huitc

**Comment by mzfr** [comment]
@687766616e 	We are still confused about what your request is. Can you please explain it properly.

**Comment by 687766616e** [comment]
edited

**Comment by 687766616e** [comment]
example
fofa.so: `domain=gogoro.com`
https://fofa.so/result?qbase64=ZG9tYWluPSJnb2dvcm8uY29tIg%3D%3D&full=true

**Comment by 687766616e** [comment]
adding `&full=true` to the end of the url can get you more history about that (normal: 1year)

(google translated 😅
