### ISSUE TITLE
speed [enhancement]

### ISSUE THREAD

**Issue by Luci-d** [TypeError/domained#59]
Check out a [spyse API](https://spyse.com) it could be a nice addition to your tool. from my experience, it works faster than most sub finders with the same output.

**Comment by mzfr** [comment]
It's paid right?

**Comment by Luci-d** [comment]
> It's paid right?

They provide some amount of data for free, but yeah, to make some big stuff, you need to buy extra queries. I think if you try to talk to them, you can come to a certain agreement on special conditions.

**Comment by hazcod** [comment]
@Luci-d are you sure? I mentions 0 subdomains for either ironpeak.be or venclave.com , which are found using other OSS tools.

**Comment by Luci-d** [comment]
> @Luci-d are you sure? I mentions 0 subdomains for either ironpeak.be or venclave.com , which are found using other OSS tools.

That's weird. It's beta so you might cause some problems. Try to contact support team. usually they give free credits for inconveniences.

**Comment by mzfr** [comment]
It would be better if we don't use this site since it's not free, also might have some issues using free version of it

**Comment by Luci-d** [comment]
> It would be better if we don't use this site since it's not free, also might have some issues using free version of it

It's up to you. I'm interested in such all-in-one services, so i suggesting to check it, and maybe you will find it useful.
